### ISSUE TITLE
Проработать тред

### ISSUE THREAD

**Issue by enchantinggg4** [dota2classic/tracker#26]
Сейчас есть 2 типа тредов: 
Форумный - где ограниченное количество сообщений на странице + пагинация
Чатовый - где неограниченное количество сообщений, которые подгружаются скроллом

Нужно реализовать курсор + скроллинг + виртуализацию хоть какую-то для чатовых

+ Для чатовых: подскролливать только если мы заснапились к концу, чтобы можно было листать наверх
Показывать плашку "х" новых сообщений

**Comment by wrongindex** [comment]
https://ant.design/components/list
Вот тут есть лист с виртуализацией, который работает напрямую с api.
